version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo
    env_file:
      - ./app.env

    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/mongodb
volumes:
  mongodb: